create table if not exists PERSON
(
    PERSON_ID int generated by default as identity,
    NAME      VARCHAR(255),
    primary key(PERSON_ID)
);

create table if not exists WIDGET
(
    ID       int generated by default as identity,
    NAME      VARCHAR(255),
    PERSON_ID int,
    primary key(ID)
);

create table if not exists TEAM
(
    TEAM_ID int generated by default as identity,
    NAME    VARCHAR(255),
     primary key(TEAM_ID)
);

create table if not exists MEMBER
(
 MEMBER_ID  int generated by default as identity,
    NAME      VARCHAR(255),
    TEAM_ID   int,
    primary key( MEMBER_ID)
);

create table if not exists PRODUCTS
(
    ID     int generated by default as identity,
    NAME  VARCHAR(255),
    PRICE DOUBLE,
     primary key( ID)
);

create table if not exists BOOK
(
    BOOK_ID int generated by default as identity,
    ACTIVE  BOOLEAN default TRUE,
    NAME    VARCHAR(255),
     primary key( BOOK_ID)
);
create table if not exists USERS
(
    ID    int generated by default as identity,
    AGE   INTEGER,
    EMAIL VARCHAR(255),
    NAME  VARCHAR(255),
     primary key( ID)
);
create table if not exists TBLORDER
(
    ORDER_ID   int generated by default as identity,
    CREATEDON  timestamp,
    MEMBER_ID  int,
    NAME       varchar(255),
    ORDER_TYPE int
);

create index if not exists "NCI_id_type_createdOn"
    on TBLORDER (MEMBER_ID, ORDER_TYPE, CREATEDON);

